// Code generated by jsonrpc2. DO NOT EDIT.
//go:generate jsonrpc2-gen -f ../../jsonrpc2.yaml -I UserAPI -I ProjectAPI -I LambdaAPI
package handlers

import (
	"context"
	"encoding/json"
	jsonrpc2 "github.com/reddec/jsonrpc2"
	api "github.com/reddec/trusted-cgi/api"
)

func RegisterUserAPI(router *jsonrpc2.Router, wrap api.UserAPI, typeHandler interface {
	ValidateToken(ctx context.Context, value *api.Token) error
}) []string {
	router.RegisterFunc("UserAPI.Login", func(ctx context.Context, params json.RawMessage, positional bool) (interface{}, error) {
		var args struct {
			Arg0 string `json:"login"`
			Arg1 string `json:"password"`
		}
		var err error
		if positional {
			err = jsonrpc2.UnmarshalArray(params, &args.Arg0, &args.Arg1)
		} else {
			err = json.Unmarshal(params, &args)
		}
		if err != nil {
			return nil, err
		}
		return wrap.Login(ctx, args.Arg0, args.Arg1)
	})

	router.RegisterFunc("UserAPI.ChangePassword", func(ctx context.Context, params json.RawMessage, positional bool) (interface{}, error) {
		var args struct {
			Arg0 *api.Token `json:"token"`
			Arg1 string     `json:"password"`
		}
		var err error
		if positional {
			err = jsonrpc2.UnmarshalArray(params, &args.Arg0, &args.Arg1)
		} else {
			err = json.Unmarshal(params, &args)
		}
		if err != nil {
			return nil, err
		}
		err = typeHandler.ValidateToken(ctx, args.Arg0)
		if err != nil {
			return nil, err
		}
		return wrap.ChangePassword(ctx, args.Arg0, args.Arg1)
	})

	return []string{"UserAPI.Login", "UserAPI.ChangePassword"}
}
